# -*- coding: utf-8 -*-
"""task_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Wz2Bw6RojIiH8MXNuR0y4_JPMuBg11k

Необходимо составить максимально лаконичный код, который осуществлял бы построение выборочной функции распределения для заданной выборки и производил бы оценку выборочной квантили для заданной вероятности. Чем короче код, тем лучше
"""

import numpy as np, matplotlib.pyplot as plt
sample = [*map(float,input().split())] #задаем выборку
x = np.linspace(min(sample), max(sample), len(sample)) #задаем точки между минимумом и максимумом
plt.step(x, [sum(i <= a for i in sample)/len(sample) for a in x]) #для каждой точки a считаем долю элементов выборки, не превосходящих a
p = float(input()) #заданная вероятность
print(np.quantile(sample, p))

